name: Commit cheat

on:
  push:
    branches:
      - master

  schedule:
    - cron: "0 1/1 * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Set global directory
        run: git config --global --add safe.directory /github/workspace

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update file
        run: |
          cat > LAST_UPDATED
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --global user.name "mocamokito"
          git config --global user.email "mocamokito@gmail.com"
          git add .
          git commit -m `date '+%Y-%m-%dT%H:%M:%SZ'`

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
